version: "3.7"

services:
  rabbitmq:
    image: rabbitmq-che
    container_name: 'rabbitmq'
    restart: unless-stopped
    networks:
      - Filo
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    # command:
    #   sh -c "rabbitmq-plugins enable rabbitmq_consistent_hash_exchange"
    # volumes: 
    #   - rabbitmq:/var/lib/rabbitmq

networks:
  Filo:
    name: filo-network

# volumes:
  # rabbitmq:
  #   driver: local
 
  